version: "3.8"

services:
  fastapi:
    image: python:3.9-slim
    container_name: fastapi-app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    working_dir: /app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - MONGO_URL=mongodb://mongo:27017
    depends_on:
      - mongo
    networks:
      - fastapi-network

  mongo:
    image: mongo
    container_name: mongodb-container
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
    networks:
      - fastapi-network

networks:
  fastapi-network:
    driver: bridge
